### ISSUE TITLE
Assert bug: notification name length exceeded maximum allowed value

### ISSUE THREAD

**Issue by AnnaShaleva** [flamingo-finance/flamingo-contract-swap#10]
**Describe the bug**
There are several [Assert](https://github.com/flamingo-finance/flamingo-contract-swap/blob/master/Swap/flamingo-contract-swap/FlamingoSwapPair/FlamingoSwapPairContract.Helper.cs#L34) helpers inside the Flamingo contract. All of these halpers use `Notify("Fault:" + message);` construction, i.e. `System.Runtime.Notify` syscall with the `"Fault:" + message` notification name.

The maximum allowed length for the notification name is 32 (see [the link](https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/ApplicationEngine.Runtime.cs#L19)). However, [method Mint](https://github.com/flamingo-finance/flamingo-contract-swap/blob/master/Swap/flamingo-contract-swap/FlamingoSwapPair/FlamingoSwapPairContract.cs#L336) uses `Assert(liquidity > 0, "INSUFFICIENT_LIQUIDITY_MINTED");`, so the resulting notification name is `Fault:INSUFFICIENT_LIQUIDITY_MINTED` with the length = 35. This notification will never be emitted because the invocation will be FAULTed due to bad name length.

Please, check that all your notifications names have length <= 32.

**Expected behavior**
All notifications emitted by `Assert` functions have the proper length <= 32.

**Platform:**
 - Version: RC1

**Comment by erikzhang** [comment]
I think you should use `Log` instead of `Notify`.

**Comment by cloud8little** [comment]
> I think you should use `Log` instead of `Notify`.

But the log did not do anything.
