### ISSUE TITLE
NEP-17 spec violation

### ISSUE THREAD

**Issue by cschuchardt88** [flamingo-finance/flamingo-contract-swap#37]
Some wallets don't support your tokens, because you don't follow NEP-17 specification which states

https://github.com/neo-project/proposals/blob/master/nep-17.mediawiki#user-content-symbol
> SHOULD be limited to uppercase Latin alphabet (i.e. the 26 letters used in English)

https://github.com/flamingo-finance/flamingo-contract-swap/blob/a3586ebcb4742edc9855d09d956c40257c1ec6c5/Swap/flamingo-contract-swap/FlamingoSwapPair/FlamingoSwapPairContract.Admin.cs#L33

is not following the specification along with other tokens flamingo finance has. To be honest all wallets shouldn't support your tokens.

**Comment by adrian-fjellberg** [comment]
Thank you for opening an isssue.

As you quoted yourself from form the specification:
> SHOULD be limited to uppercase Latin alphabet

It clearly states "SHOULD", which does means the specification does not require it. 

> "SHOULD" This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.

  https://datatracker.ietf.org/doc/html/rfc2119

**Comment by cschuchardt88** [comment]
This isnt RFC specification
> Key words for use in RFCs to Indicate Requirement Levels

If this is the case than you should be using NEP-15
>The supportedstandards field describes which standard it supports, such like NEP or RFC. It must be an array. In order to make smart contracts or other clients understand correctly, all NEPs must be capitalized. NEP and number must be connected with -. For example: "supportedstandards": ["NEP-11", "NEP-17", "RFC 1035"].

Adding `RFC 2119` to `supportedstandards`

See spec NEP-1 which states, 
>A Standards Track NEP describes any change that affects most or all NEO implementations, such as a change to the network protocol, a change in block or transaction validity rules, proposed application standards/conventions, or any change or addition that affects the interoperability of applications using NEO.

That doesnt justify or say anywhere about, that NEP follows RFC standards.

It was very clear in NEP-15 how NEP should be used.  See spec NEP-1 which states
> A Standards Track NEP describes any change that affects most or all NEO implementations, such as a change to the network protocol, a change in block or transaction validity rules, proposed application standards/conventions, or any change or addition that affects the interoperability of applications using NEO. 

That doesnt justify or say anywhere about, that NEP follows RFC standards.

so we will use english as the definition here, and SHOULD means
>used to indicate obligation, duty, or correctness, typically when criticizing someone's actions.
"he should have been careful"

Whats the point of NEP if not followed? so it will be the wild wild west? If you want people to use NEO, it needs to be good, Clear and precise definitions that specify the standard. None of this "what I think it means" . Its very clear and straight to the point. Also keyword is `recommended` for 3-8 characters, thats very clear. Which you dont violate.  So if you want to assume words its even more clear when they say `recommended` and since they didnt use that word, `SHOULD` will be used as what the english definition says.

That is why i say maybe a new NEP is appropriate here
